id: IEE3F9B1F
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T18:59:00.369129'
last_modified: '2022-05-27T18:59:00.369142'
parser: null
source_metadata:
  title: 'MSV 6,00: Uttaragrantha 2'
  language: bo
  base:
    fE330:
      title: Uttaragrantha 2
      base_file: fE330.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
